### ISSUE TITLE
Instantiated IngressPerAppRequirer prior to knowledge of TLS

### ISSUE THREAD

**Issue by MichaelThamm** [canonical/loki-coordinator-k8s-operator#68]
### Bug Description

The `IngressPerApp` class from the `charms.traefik_k8s.v2.ingress` lib [is instantiated](https://github.com/canonical/loki-coordinator-k8s-operator/blob/67d241c2c793e7ca11f0654463a99378937092b1/src/charm.py#L65) with a port from the `internal_url` which [is conditional](https://github.com/canonical/loki-coordinator-k8s-operator/blob/67d241c2c793e7ca11f0654463a99378937092b1/src/charm.py#L143) based on the existence of certs on disk (TLS). These certs are not on disk yet, once the `IngressPerApp` is instantiated and therefore the port that is passed in is `8080` instead of the expected `443`. This results in the databag having an outdated port:

`juju show-unit traefik/0 | yq -r '."traefik/0"."relation-info"'`:

```yaml
- relation-id: 100
  endpoint: ingress
  related-endpoint: ingress
  application-data:
    model: '"cos"'
    name: '"loki"'
    port: "8080"
```

### To Reproduce

Update loki-coordinator's charm.py __init__ to:

```python
        print(self.internal_url)
        self.ingress = IngressPerAppRequirer(
            charm=self,
            port=urlparse(self.internal_url).port,
            strip_prefix=True,
            scheme=lambda: urlparse(self.internal_url).scheme,
        )
        self.alertmanager_consumer = AlertmanagerConsumer(self, relation_name="alertmanager")
        self.coordinator = Coordinator(
            # snip ...
        )
        print(self.coordinator.nginx.are_certificates_on_disk)
```

Where the values of the print statements are:

`self.internal_url`: `http://loki-0.loki-endpoints.cos.svc.cluster.local:8080`
`self.coordinator.nginx.are_certificates_on_disk)`: `False`

### Environment

```yaml
bundle: kubernetes
applications:
  loki:
    charm: local:loki-coordinator-k8s-1
    scale: 1
    constraints: arch=amd64
    trust: true
  loki-backend:
    charm: loki-worker-k8s
    channel: 2/edge
    revision: 48
    resources:
      loki-image: 3
    scale: 1
    options:
      role-backend: true
    constraints: arch=amd64 tags=anti-pod.app.kubernetes.io/name=loki-backend,anti-pod.topology-key=kubernetes.io/hostname
    storage:
      loki-persisted: kubernetes,1,1024M
    trust: true
  loki-read:
    charm: loki-worker-k8s
    channel: 2/edge
    revision: 48
    resources:
      loki-image: 3
    scale: 1
    options:
      role-read: true
    constraints: arch=amd64 tags=anti-pod.app.kubernetes.io/name=loki-read,anti-pod.topology-key=kubernetes.io/hostname
    storage:
      loki-persisted: kubernetes,1,1024M
    trust: true
  loki-s3-integrator:
    charm: s3-integrator
    channel: 2/edge
    revision: 157
    scale: 1
    options:
      bucket: loki
      credentials: secret:d1dd0fnmp25c7650qgrg
      endpoint: http://192.168.88.12:8080
    constraints: arch=amd64
    trust: true
  loki-write:
    charm: loki-worker-k8s
    channel: 2/edge
    revision: 48
    resources:
      loki-image: 3
    scale: 1
    options:
      role-write: true
    constraints: arch=amd64 tags=anti-pod.app.kubernetes.io/name=loki-write,anti-pod.topology-key=kubernetes.io/hostname
    storage:
      loki-persisted: kubernetes,1,1024M
    trust: true
  self-signed-certificates:
    charm: self-signed-certificates
    channel: 1/edge
    revision: 308
    scale: 1
    constraints: arch=amd64
  traefik:
    charm: traefik-k8s
    channel: latest/edge
    revision: 236
    base: ubuntu@20.04/stable
    resources:
      traefik-image: 161
    scale: 1
    constraints: arch=amd64
    storage:
      configurations: kubernetes,1,1024M
    trust: true
relations:
- - self-signed-certificates:certificates
  - traefik:certificates
- - loki:s3
  - loki-s3-integrator:s3-credentials
- - loki:loki-cluster
  - loki-read:loki-cluster
- - loki:loki-cluster
  - loki-write:loki-cluster
- - loki:loki-cluster
  - loki-backend:loki-cluster
- - traefik:ingress
  - loki:ingress
```

### Relevant log output

```shell
N/A
```
